apiVersion: apps/v1
kind: Deployment
metadata:
  name: wlactiondemo01-deployment
spec:
  selector:
    matchLabels:
      app: wlactiondemo01-pod
  template:
    metadata:
      labels:
        app: wlactiondemo01-pod
    spec:
      containers:
      - name: wlactiondemo01-container
        image: sidlabacr03.azurecr.io/wlactiondemo01:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
