replicaCount: 2
k8s:
  namespace: "default"
app:
  name: "wlactiondemo01-api"
service:
  port: "5000"
metrics:
  port: "5001"
cpu:
  target: "100m"
  #This is 85% of the cpu limit set.
memory:
  target: "413Mi"
  #This is 85% of the memory limit set.
pv:
  name: "wlactiondemo0sc"
pvc:
  name: "wlactiondemo0pvc"

image:
  repository: "sidlabacr03.azurecr.io/wlactiondemo01"
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
imagePullSecrets:
  name: acr-auth

#service:
#  type: ClusterIP
#  port: 80

resources:
  limits:
    cpu: 135m
    memory: 486Mi
  requests:
    cpu: 75m
    memory: 270Mi

#autoscaling:
#  enabled: false
#  minReplicas: 1
#  maxReplicas: 100
#  targetCPUUtilizationPercentage: 80
#  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
