name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  HELM_EXPERIMENTAL_OCI: 1

jobs:

  build_push_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sidlabacr03.azurecr.io/wlactiondemo01:latest
   
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: sidlabacr03 
        # Container registry password
        password: JFHb3IFYta5QZxR44XzU6j=ch6OhS9GI
        # Container registry server url
        login-server: sidlabacr03.azurecr.io
    - name: Push the Docker image
      run: docker push sidlabacr03.azurecr.io/wlactiondemo01:latest
 
    - name: Helm tool installer
      uses: Azure/setup-helm@v1
      with:
        # Version of helm
        version: 3.3.1        
    - name: Login to ACR using HELM
      run: |
        echo $ | helm registry login sidlabacr03.azurecr.io --username sidlabacr03 --password JFHb3IFYta5QZxR44XzU6j=ch6OhS9GI
    - name: Package Helm Chart
      run: helm package ./helm/wlactiondemo01-api
    - name: save helm chart to local registry
      run: |
        helm chart save ./wlactiondemo01-api-0.1.0.tgz sidlabacr03.azurecr.io/charts-wlactiondemo01-api:latest        
    - name: Helm Chart Push
      run: helm chart push sidlabacr03.azurecr.io/charts-wlactiondemo01-api:latest


#  deploy:
#    runs-on: ubuntu-latest
#    needs: build_push_image # Will wait for the execution of the previous job
#    
#    steps:
#    - uses: actions/checkout@v2
##    - name: Azure Kubernetes set context
##      uses: Azure/aks-set-context@v1.1
##      with:
##        # Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`
##        creds: ${{ secrets.AKS_CREDS }}
##        # Resource Group Name
##        resource-group: Intel_RG
##        # AKS Cluster Name
##        cluster-name: sidlabaks01

#    - name: Kubernetes set context
#      uses: Azure/k8s-set-context@v1
#      with:
#        kubeconfig: ${{secrets.KUBECONFIG}}  
#      id: login

        
#    - name: Apply AKS Deployment
#      run: kubectl apply -f deployment.yaml
      
#    - name: Apply AKS Deployment
#      run: kubectl apply -f service.yaml
  deploy:
    runs-on: ubuntu-latest
    needs: build_push_image # Will wait for the execution of the previous job
    
    steps:
    - uses: actions/checkout@v2
    - name: Kubernetes set context
      uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{secrets.KUBECONFIG}}  
      id: login
      
    - name: Helm tool installer
      uses: Azure/setup-helm@v1
      with:
        # Version of helm
        version: 3.3.1
        
    - name: Login to ACR using HELM
      run: |
        echo $ | helm registry login sidlabacr03.azurecr.io --username sidlabacr03 --password JFHb3IFYta5QZxR44XzU6j=ch6OhS9GI
        
    - name : Set Helm Env Var
      run : export HELM_EXPERIMENTAL_OCI=1  
      
    - name: Helm Chart Pull
      run: helm chart pull sidlabacr03.azurecr.io/charts-wlactiondemo01-api:latest
   
    - name: Helm Chart Move
      run: helm chart export sidlabacr03.azurecr.io/charts-wlactiondemo01-api:latest --destination ./install
      
    - name: Helm Chart Install
      run: helm upgrade --namespace ns-dev --install --set image.tag=latest wlactiondemo01-api ./install/wlactiondemo01-api # release name chart name
      
