name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag inteltrainingacr02.azurecr.io/wlactiondemo01:latest
   
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: inteltrainingacr02 
        # Container registry password
        password: HLZa5bnTqoy34=3CbvjqBQhBAL3PnSwe
        # Container registry server url
        login-server: inteltrainingacr02.azurecr.io
    - name: Push the Docker image
      run: docker push inteltrainingacr02.azurecr.io/wlactiondemo01:latest
